Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Style/Encoding:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableName:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
